name: Code analysis
on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          generate-job-summary: false

      - name: Execute Detekt task
        run: ./gradlew detekt

      - name: Archive report
        uses: actions/upload-artifact@v3
        with:
          name: Detekt report
          path: build/reports/detekt/

      - name: Add report to action summary
        run: cat build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY
